// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test2', async function() {
    await driver.get("https://cadastrocars.vercel.app/")
    await driver.manage().window().setRect({ width: 1051, height: 798 })
    await driver.findElement(By.css(".carItem:nth-child(1) .pointButton")).click()
    await driver.findElement(By.css(".pointWindowBtn:nth-child(1)")).click()
    await driver.findElement(By.css(".yearField")).click()
    await driver.findElement(By.css(".yearField")).sendKeys("2020")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".priceField")).sendKeys("100000")
    await driver.findElement(By.css(".full")).click()
    //Verificar se o primeiro carro da lista teve o ano e o preço alterado para 2020 e R$100000,00
  })
})
