// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("https://cadastrocars.vercel.app/")
    await driver.manage().window().setRect({ width: 1053, height: 799 })
    await driver.findElement(By.linkText("Cadastrar")).click()
    await driver.findElement(By.css(".brandField")).click()
    {
      const dropdown = await driver.findElement(By.css(".brandField"))
      await dropdown.findElement(By.xpath("//option[. = 'Toyota']")).click()
    }
    await driver.findElement(By.css(".modelField")).click()
    await driver.findElement(By.css(".modelField")).sendKeys("Corolla")
    await driver.findElement(By.css(".yearField")).click()
    await driver.findElement(By.css(".yearField")).sendKeys("2011")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".kmField")).click()
    await driver.findElement(By.css(".kmField")).sendKeys("100000")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".priceField")).sendKeys("50000")
    await driver.findElement(By.css(".full")).click()
    //Verificar se foi adicionado um novo carro: Toyota Corolla 2011 100000km R$50000,00
  })
})
